services:
  gh-pages:
    build:
      context: https://github.com/github/pages-gem.git#v232
      dockerfile: Dockerfile.alpine
    command: sh -c "bundle install && jekyll serve --destination /tmp/_site --watch --force_polling -H 0.0.0.0 -P 4000"
    ports:
      - "4000:4000"
    volumes:
      - type: bind
        source: ./docs
        target: /src/site
      - type: bind
        source: ./Gemfile
        target: /src/site/Gemfile
    environment:
      - PAGES_REPO_NWO=username/repo-name