name: Publish to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install pandas

      - name: Build pages
        run: python3 scripts/build_pages.py

      - name: Build index
        run: python3 scripts/build_index_md.py

      - name: デバッグ用に生成されたファイルを一覧表示
        run: |
          echo "docsディレクトリの内容:"
          ls -la docs/
          if [ -d "docs/data" ]; then
            echo "docs/dataディレクトリの内容:"
            ls -la docs/data/
          else
            echo "警告: docs/dataディレクトリが存在しません"
          fi

          if [ -f "docs/index.md" ]; then
            echo "index.mdは存在します"
          else
            echo "警告: index.mdが存在しません"
          fi

      - name: gh-pagesブランチをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: docsをgh-pagesに同期
        run: |
          mkdir -p gh-pages/docs
          cp -f docs/index.md gh-pages/docs/

          mkdir -p gh-pages/docs/data
          cp -rf docs/data/* gh-pages/docs/data/

      - name: Commit and push if changes exist
        run: |
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name github-actions[bot]
            git config user.email 41898282+github-actions[bot]@users.noreply.github.com
            git add docs/index.md docs/data/
            git commit -m "update: $(date '+%Y-%m-%d')"
            git push origin gh-pages
          else
            echo "No changes to commit."
          fi