name: 2. Build and Publish to GitHub Pages

on:
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install pandas

      - name: Build pages
        run: python3 scripts/build_pages.py

      - name: Build index
        run: python3 scripts/build_index_md.py

      - name: Checkout gh-pages branch
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Sync docs to gh-pages
        run: |
          mkdir -p gh-pages/docs
          cp -f docs/index.md gh-pages/docs/
          mkdir -p gh-pages/docs/data
          cp -rf docs/data/* gh-pages/docs/data/

      - name: Commit and push if changes exist
        run: |
          cd gh-pages
          if [[ -n $(git status --porcelain) ]]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add .
            git commit -m "Updated: $(date '+%Y-%m-%d')"
            git push origin gh-pages
          else
            echo "No changes to commit."
          fi