name: Publish to gh-pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build_and_publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install Python dependencies
        run: |
          pip install pandas

      - name: Build pages
        run: python3 scripts/build_pages.py

      - name: Build index
        run: python3 scripts/build_index_md.py

      - name: デバッグ用に生成されたファイルを一覧表示
        run: |
          echo "docsディレクトリの内容:"
          ls -la docs/
          if [ -d "docs/data" ]; then
            echo "docs/dataディレクトリの内容:"
            ls -la docs/data/
          else
            echo "警告: docs/dataディレクトリが存在しません"
          fi

          if [ -f "docs/index.md" ]; then
            echo "index.mdは存在します"
          else
            echo "警告: index.mdが存在しません"
          fi

      # gh-pagesブランチが存在するか確認し、存在しなければ作成
      - name: 必要に応じてgh-pagesブランチを作成
        run: |
          if ! git ls-remote --heads origin gh-pages | grep gh-pages; then
            git checkout --orphan gh-pages
            git rm -rf .
            echo "# プロジェクトページ" > index.md
            git add index.md
            git config user.name "github-actions[bot]"
            git config user.email "github-actions[bot]@users.noreply.github.com"
            git commit -m "gh-pagesの初期コミット"
            git push origin gh-pages
            git checkout main
          fi

      - name: gh-pagesブランチをチェックアウト
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: docsをgh-pagesに同期
        run: |
          # gh-pagesにdataディレクトリがなければ作成
          mkdir -p gh-pages/data

          # index.mdをコピー
          if [ -f "docs/index.md" ]; then
            cp docs/index.md gh-pages/
          else
            echo "警告: docs/index.mdが存在しないため、コピーをスキップします"
          fi

          # dataディレクトリの内容をコピー
          if [ -d "docs/data" ]; then
            cp -r docs/data/* gh-pages/data/
          else
            echo "警告: docs/dataディレクトリが存在しないため、コピーをスキップします"
          fi

      - name: デバッグ用にgh-pagesのファイルを一覧表示
        working-directory: gh-pages
        run: |
          echo "コミット準備完了のファイル:"
          ls -la
          if [ -d "data" ]; then
            echo "dataディレクトリの内容:"
            ls -la data/
          fi

      - name: gh-pagesにコミットしてプッシュ
        working-directory: gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          git add .
          git status

          if git diff --staged --quiet; then
            echo "デプロイする変更はありません"
          else
            git commit -m "$GITHUB_SHAからのサイトデプロイ"
            git push origin gh-pages
          fi