name: 1. Update CSV Files

on:
  schedule:
    - cron: '0 0 * * *'  # 毎日0:00（UTC）
  workflow_dispatch:

jobs:
  update-csv-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download & Extract CSVs
        run: bash scripts/download_csv.sh

      - id: commit_and_push
        name: Commit and push if changes exist
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "Updated: $(date '+%Y-%m-%d')"
            git pull --rebase
            git push origin HEAD
            echo "changes_exist=true" >> $GITHUB_OUTPUT
          else
            echo "No changes to commit."
            echo "changes_exist=false" >> $GITHUB_OUTPUT
          fi

      - name: Trigger Build & Publish Workflow if changes exist
        if: steps.commit_and_push.outputs.changes_exist == 'true'
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: gh workflow run "2. Build and Publish to GitHub Pages"