name: Update CSV Files

on:
  # 毎日 12:00 JST（3:00 UTC）
  schedule:
    - cron: '0 3 * * *'
  # 手動トリガー
  workflow_dispatch:

jobs:
  update-csv-files:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Download & Extract CSVs
        run: bash scripts/download_csv.sh

      - name: Commit and push if changes exist
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"

          if [[ -n $(git status --porcelain) ]]; then
            git add .
            git commit -m "update: $(date '+%Y-%m-%d')"
            git pull --rebase
            git push origin HEAD
          else
            echo "No changes to commit."
          fi